
import * as LoadingConstants from './LoadingStateConstants';
import Firebase, { db, storage } from '../../config/Firebase';
var POSITION_OFFSET = .05 // 5 cm
import Items from './firebaseAR'

/**
 * Data model for 3D Objects provided as input to ModelItemRenderer. The schema is as follows:
 * name - string key used to identify / retreive this model from this model array
 * selected - Is this model currently selected by the user. Used in identifying which model to execute action from Context Menu (example - remove action)
 * loading - initial loading state. Can toggle to LOADING, LOADED, ERROR when user tries to add the model to the system
 * icon_img - the icon that will be shown on the listview at the bottom for this model
 * obj - path for VRX format obj for this model checked in locally
 * materials - materials used in the VRX model (Currently unused since moving to VRX format)
 * animation - VRX skeletal animations that are baked in to the model definition itself
 * scale - initial scale of the model 
 * position - initial position of the model. Primarily used to configure how close to the ground this model should be rendered (cloud rendered higher, pumpkin renderer lower)
 * type - VRX / OBJ format
 * physics - props for physics body of the model
 * shadow_width - width of the shadow plane to be configured depending on size of the model
 * shadow_height - height of the shadow plane to be configured depending on size of the model
 * spotlight_position_y - height above the object, where the spotlight should be placed at. Different for each model depending on size of the model
 * lighting_model - lighting model for this object
 * resources - all the materials (textures) used in this object, that are checked in locally.
 */
// global.object1 = ['']
// var object1 = ''

// // Create a reference to the file we want to download

//   var starsRef = storage.refFromURL('gs://interiorproject-2567f.appspot.com/3d models/untitled.mtl');

// // Get the download URL
// starsRef.getDownloadURL().then((url) => {
//    object1 = url
//    console.log(object1)

// }).catch(function(error) {

//   // A full list of error codes is available at
//   // https://firebase.google.com/docs/storage/web/handle-errors
//   switch (error.code) {
//     case 'storage/object-not-found':
//       console.log( "File doesn't exist")
//       break;

//     case 'storage/unauthorized':
//       console.log( "User doesn't have permission to access the object")
//       // User doesn't have permission to access the object
//       break;

//     case 'storage/canceled':
//       console.log( "User canceled the upload")
//       // User canceled the upload
//       break;



//     case 'storage/unknown':
//       console.log( "User unkown")
//       break;
//   }
// });


//console.log( storage.refFromURL('gs://interiorproject-2567f.appspot.com/3d models/untitled.obj').getDownloadURL(), "SADASD")

var ModelItems = [

  {

    "name": "dragon_anim",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/OldChair/obj/oldChair.jpg"),

    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2FoldChair%2FobjChair.obj?alt=media&token=f76c092a-8bc2-4ab4-9c31-d506e3c665df' },
    "materials": "white",

    // "animation":{name:"01", delay:0, loop:true, run:true},
    "scale": [.2, .2, .2],
    "position": [0, 5 * POSITION_OFFSET, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "shadow_width": 10.5,
    "shadow_height": 10.5,
    "spotlight_position_y": 19,
    "lighting_mode": "IBL",
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 8,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2FoldChair%2FobjChair.mtl?alt=media&token=5f59e956-a7f7-424c-a903-62691a64af99' },],

  },

  {
    "name": "pumpkin_man",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/2personsofa/2personsofa.png"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2F2personsofa%2F2personsofa.obj?alt=media&token=f4b37fa4-e341-4a0f-96d5-e24d571541bb' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.3, .3, .3],
    "position": [0, 0, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "shadow_width": 2,
    "shadow_height": 4.5,
    "spotlight_position_y": 18.2,
    // "shadowfarz": 7.3,
    "shadow_width": 18.5,
    "shadow_height": 10.5,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 5,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2F2personsofa%2F2personsofa.mtl?alt=media&token=e9426368-97df-45c9-bdb3-af37ecd1ae83' },],
  },
  // {
  //   "name": "turkeyman_anim",
  //   "selected": false,
  //   "loading": LoadingConstants.NONE,
  //   "icon_img":require("./res/models/3personsofa/3person.jpg"),
  //   "obj": require("./res/models/3personsofa/3person.obj"),
  //   "materials": "white",
  //   "animation":{name:"02", delay:0, loop:true, run:true},
  //   "scale": [.3, .3, .3],
  //   "position" : [-0.1, 0, 0],
  //   "type" : "OBJ",
  //   "physics": undefined,
  //   "ref_pointer": undefined,
  //   "shadow_width": 8,
  //   "shadow_height": 3,
  //   "spotlight_position_y": 29.2,
  //  // "shadowfarz": 12.3,
  //   "shadow_width": 29.5,
  //   "shadow_height": 10.5,
  //   "posx0" : -0.2,
  //   "posx1" : 0.6,
  //   "posx2" : 1.4,
  //   "posx3" : 2.2,
  //   "posx4" : 3.0,
  //   "posy" : 5,
  //   "posz" : 0,
  //   "resources": [require('./res/models/3personsofa/3person.mtl')],
  // },

  {
    "name": "emoji_smile",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/roundtable/roundtable.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Froundtable%2Froundtable.obj?alt=media&token=23d791da-e3e3-4138-b3b3-c0e5a9b49f37' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.2, .2, .2],
    "position": [0, .497823 + POSITION_OFFSET, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 25.2,
    "lighting_mode": "IBL",
    "shadow_width": 20.5,
    "shadow_height": 10.5,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Froundtable%2Froundtable.mtl?alt=media&token=e4ed84b2-649b-43b0-8315-ddd5d6fe9127' },],
  },
  // {
  //   "name": "emoji_smile",
  //   "selected": false,
  //   "loading": LoadingConstants.NONE,
  //   "icon_img":require("./res/models/back_sofa/dinnigtable.JPG"),
  //   "obj": {uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fdiningtable%2Funtitled.obj?alt=media&token=a6bf14c2-3794-43e4-99fb-d01cd1c182a0'},
  //   "materials": "white",
  //   "animation":{name:"02", delay:0, loop:true, run:true},
  //   "scale": [.2, .2, .2],
  //   "position" : [0, .497823 + POSITION_OFFSET, 0],
  //   "type" : "OBJ",
  //   "physics": undefined,
  //   "ref_pointer": undefined,
  //   "spotlight_position_y": 25.2,
  //   "lighting_mode": "IBL",
  //   "shadow_width": 20.5,
  //   "shadow_height": 10.5,
  //   "posx0" : -1.6,
  //   "posx1" : -0.8,
  //   "posx2" : 0,
  //   "posx3" : 0.8,
  //   "posx4" : 1.6,
  //   "posy" : 3,
  //   "posz" : 0,
  //   "resources": [{uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fdiningtable%2Funtitled.mtl?alt=media&token=7d80ab7d-5157-48f2-8283-a684bebef1ec'},],
  // },
  {
    "name": "emoji_smile",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/table/table.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Ftable%2Funtitled.obj?alt=media&token=f2d5b955-b63b-43ea-9fea-f3f2e56d4234' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.2, .2, .2],
    "position": [0, .497823 + POSITION_OFFSET, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 25.2,
    "lighting_mode": "IBL",
    "shadow_width": 20.5,
    "shadow_height": 10.5,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Ftable%2Funtitled.mtl?alt=media&token=c409cb93-bad0-489e-9906-a597c5d88dd0' },],
  },
  {
    "name": "emoji_sad",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/chair/chair.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fchair%2Fchair.obj?alt=media&token=f0bfc6a5-38a1-4a2a-a8a9-70e92df853ab' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.2, .2, .2],
    "position": [0, .494890 + POSITION_OFFSET, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 20.2,
    "lighting_mode": "IBL",
    "shadow_width": 20.5,
    "shadow_height": 10.5,
    "posx0": -2.6,
    "posx1": -1.8,
    "posx2": -1.0,
    "posx3": -0.2,
    "posx4": 0.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fchair%2Fchair.mtl?alt=media&token=5a9222b0-f062-4893-9de5-74486ead5b2b' },],
  },

  {
    "name": "pug_animated",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/back_sofa/backsofa.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fback_sofa%2Fbacksofa.obj?alt=media&token=0872f9be-d8c5-4373-ada0-75a66369a765' },
    "materials": "white",
    "animation": { name: "Take 001", delay: 0, loop: true, run: true },
    "scale": [.3, .3, .3],
    "position": [0, 0, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 15.2,
    "lighting_mode": "IBL",
    "shadow_width": 10.5,
    "shadow_height": 10.5,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fback_sofa%2Fbacksofa.mtl?alt=media&token=98b0f82b-5166-45d9-8164-9ac313cfbf67' },],
  },

  {
    "name": "emoji_wow",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/chair1/chair1.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fchair1%2Fchair1.obj?alt=media&token=2cce0f55-d132-4b80-890d-d7be24a97a72' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.2, .2, .2],
    "position": [0, .494890, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 25.2,
    "lighting_mode": "IBL",
    "shadow_width": 20.5,
    "shadow_height": 10.5,
    "posx0": -3.6,
    "posx1": -2.8,
    "posx2": -2.0,
    "posx3": -1.2,
    "posx4": -0.4,
    "posy": 4,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fchair1%2Fchair1.mtl?alt=media&token=e33bb5e5-98a8-4d5a-ad3c-0c31f9943a12' },],
  },
  // {
  //   "name": "emoji_angry",
  //   "selected": false,
  //   "loading": LoadingConstants.NONE,
  //   "icon_img":require("./res/models/chair2/chair2.jpg"),
  //   "obj": require("./res/models/chair2/chair2.obj"),
  //   "materials": "white",
  //   "animation":{name:"02", delay:0, loop:true, run:true},
  //   "scale": [.2, .2, .2],
  //   "position" : [0, .494890, 0],
  //   "type" : "OBJ",
  //   "emitter_name": "EmojiAngryEmitter",
  //   "physics": undefined,
  //   "ref_pointer": undefined,
  //   "spotlight_position_y": 10.2,
  //   "lighting_mode": "IBL",
  //   "posx0" : -1.6,
  //   "posx1" : -0.8,
  //   "posx2" : 0,
  //   "posx3" : 0.8,
  //   "posx4" : 1.6,
  //   "posy" : 4,
  //   "posz" : 0,
  //   "resources": [require('./res/models/chair2/chair2.mtl')],
  // },
  {
    "name": "emoji_kiss",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/chotasofa/narm.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fchotasofa%2Funtitled.obj?alt=media&token=cc0f7fa0-062f-4104-bf70-7f679bfd02fa' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.2, .2, .2],
    "position": [0, .494890 + POSITION_OFFSET, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 20.2,
    "lighting_mode": "IBL",
    "shadow_width": 20.5,
    "shadow_height": 10.5,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 5,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fchotasofa%2Funtitled.mtl?alt=media&token=18fe546c-f6ea-4ae1-9100-dcb99ad3364b' },],
  },
  {
    "name": "emoji_heart",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/couch/couch.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fcouch%2Fcouch.obj?alt=media&token=d330070a-39df-4144-884f-aec95fa433ed' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.2, .2, .2],
    "position": [0, .451719 + POSITION_OFFSET, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 15.2,
    "lighting_mode": "IBL",
    "shadow_width": 15.5,
    "shadow_height": 10.5,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fcouch%2Fcouch.mtl?alt=media&token=f4252dc3-3491-415b-9cf7-30678be176b9' },],
  },
  {
    "name": "emoji_thumbsup",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/dottedsofa/dottedsofa.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fdottedsofa%2Fdottedsofa.obj?alt=media&token=994d13fa-f91c-4467-8296-380ba392624b' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.2, .2, .2],
    "position": [0, 0.506186 + POSITION_OFFSET, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 25.2,
    "lighting_mode": "IBL",
    "shadow_width": 20.5,
    "shadow_height": 10.5,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 4,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fdottedsofa%2Fdottedsofa.mtl?alt=media&token=793a3596-1418-4afd-bb53-eb7f50f2f80e' },],
  },

  // {
  //   "name": "emoji_poop",
  //   "selected": false,
  //   "loading": LoadingConstants.NONE,
  //   "icon_img":require("./res/models/lamba_sofa/untitled.jpg"),
  //   "obj": {uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Funtitled.obj?alt=media&token=e2cd6329-69db-41c0-901a-4cf825830919'},
  //   "materials": "white",
  //   "animation":{name:"02", delay:0, loop:true, run:true},
  //   "scale": [.2, .2, .2],
  //   "position" : [0, .353032 + POSITION_OFFSET, 0],
  //   "type" : "OBJ",
  //   "physics": undefined,
  //   "ref_pointer": undefined,
  //   "spotlight_position_y": 35.2,
  //   "lighting_mode": "IBL",
  //   "shadow_width": 30.5,
  //   "shadow_height": 10.5,
  //   "posx0" : -0.2,
  //   "posx1" : 0.6,
  //   "posx2" : 1.4,
  //   "posx3" : 2.2,
  //   "posx4" : 3.0,
  //   "posy" : 4,
  //   "posz" : 0,
  //   "resources": [{uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Funtitled.mtl?alt=media&token=53f4fc4f-b8d9-4ea3-9c1a-b432e114a7c3'},],
  // },

  {
    "name": "object_star",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/seatti/seatti.png"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fseatti%2Fseatti.obj?alt=media&token=06df14b4-03ff-44f9-9e31-1b1b10f259cc' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.2, .2, .2],
    "position": [0, .939014 + POSITION_OFFSET, 0],
    "physics": undefined,
    "type": "OBJ",
    "ref_pointer": undefined,
    "lighting_mode": "IBL",
    "spotlight_position_y": 19.2,

    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fseatti%2Fseatti.mtl?alt=media&token=5dc575b8-c9fe-4fec-8dbd-0f825d48e949' },],
  },
  // {
  //   "name": "object_rainbow",
  //   "selected": false,
  //   "loading": LoadingConstants.NONE,
  //   "icon_img":require("./res/other/bed/bed.jpg"),
  //   "obj": require("./res/other/bed/bed.obj"),
  //   "materials": "white",
  //   "animation":{name:"02", delay:0, loop:true, run:true},
  //   "scale": [1, 1, 1],
  //   "position" : [0, .235285 , 0],
  //   "physics": undefined,
  //   "type" : "OBJ",
  //   "ref_pointer": undefined,
  //   "lighting_mode": "IBL",
  //   "spotlight_position_y": 25.2,
  //   "posx0" : -0.2,
  //   "posx1" : 0.6,
  //   "posx2" : 1.4,
  //   "posx3" : 2.2,
  //   "posx4" : 3.0,
  //   "posy" : 5,
  //   "posz" : 0,
  //   "resources": [require('./res/other/bed/bed.mtl')]
  // },
  {
    "name": "object_cloud",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/other/desk/desk.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fdesk%2Fdesk.obj?alt=media&token=ddef060d-5f6a-47f0-9962-cee6a1896ccd' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [0.3, 0.3, 0.3],
    "position": [0, .235285, 0],
    "physics": undefined,
    "type": "OBJ",
    "ref_pointer": undefined,
    "lighting_mode": "IBL",
    "spotlight_position_y": 19.2,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 4,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fdesk%2Fdesk.mtl?alt=media&token=68838263-c881-43b8-b386-1eb7717dcdee' },],
  },
  // {
  //   "name": "object_cloud",
  //   "selected": false,
  //   "loading": LoadingConstants.NONE,
  //   "icon_img":require("./res/other/wardrobe/wardrobe.jpg"),
  //   "obj": require("./res/other/wardrobe/wardrobe.obj"),
  //   "materials": "white",
  //   "animation":{name:"02", delay:0, loop:true, run:true},
  //   "scale": [0.3, 0.3, 0.3],
  //   "position" : [0, 0 , 0],
  //   "physics": undefined,
  //   "type" : "OBJ",
  //   "ref_pointer": undefined,
  //   "lighting_mode": "IBL",
  //   "spotlight_position_y": 29.2,
  //   "posx0" : -1.6,
  //   "posx1" : -0.8,
  //   "posx2" : 0,
  //   "posx3" : 0.8,
  //   "posx4" : 1.6,
  //   "posy" : 5,
  //   "posz" : 0,
  //   "shadow_width": 28.5,
  //   "shadow_height": 10.5,
  //   "resources": [require("./res/other/wardrobe/wardrobe.mtl") ] 
  // },
  {
    "name": "object_cloud",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/other/objchair/objchair.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fobjchair%2Fobjchair.obj?alt=media&token=5724d15d-b706-4338-99ed-82495f27ce8d' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [0.3, 0.3, 0.3],
    "position": [0, .235285, 0],
    "physics": undefined,
    "type": "OBJ",
    "ref_pointer": undefined,
    "lighting_mode": "IBL",
    "spotlight_position_y": 19.2,
    "posx0": -0.2,
    "posx1": 0.6,
    "posx2": 1.4,
    "posx3": 2.2,
    "posx4": 3.0,
    "posy": 5,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fobjchair%2Fobjchair.mtl?alt=media&token=21970184-2074-4189-85dd-c621514c14be' },],
  },
  {
    "name": "object_cloud",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/other/shelf/pandorabox.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fpandorabox%2Fpandorabox.obj?alt=media&token=9fa5ac5e-fc35-49a8-86e2-7d6cd1ffa02b' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [0.3, 0.3, 0.3],
    "position": [0, .235285, 0],
    "physics": undefined,
    "type": "OBJ",
    "ref_pointer": undefined,
    "lighting_mode": "IBL",
    "spotlight_position_y": 19.2,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fpandorabox%2Fpandorabox.mtl?alt=media&token=9d71758c-0ef5-409e-9c7f-afb406182676' },],
  },
  {
    "name": "object_cloud",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/other/stand/stand.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fstand%2Fstand.obj?alt=media&token=1ead7afd-8bf0-4274-9d98-1cf6c0ab1681' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [0.3, 0.3, 0.3],
    "position": [0, .235285, 0],
    "physics": undefined,
    "type": "OBJ",
    "ref_pointer": undefined,
    "lighting_mode": "IBL",
    "spotlight_position_y": 19.2,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fstand%2Fstand.mtl?alt=media&token=545b1de0-da30-4764-b93e-7ff3737bcaa5' },],
  },
  {
    "name": "object_cloud",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/other/standnight/nightstang.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fnightstand%2Fnightstang.obj?alt=media&token=17282e78-a61a-48ea-83b9-d23ebaaedb3d' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [0.2, 0.2, 0.2],
    "position": [0, .235285, 0],
    "physics": undefined,
    "type": "OBJ",
    "ref_pointer": undefined,
    "lighting_mode": "IBL",
    "spotlight_position_y": 19.2,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 2,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fnightstand%2Fnightstang.mtl?alt=media&token=c3851dbf-6cdd-4886-b1bf-a47eb1d2e591' },],
  },
  {
    "name": "object_cloud",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/other/desk/desk.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fdesk2%2Fdesk.obj?alt=media&token=4b808f82-1bc2-42fd-9c9c-bbe8ee934f75' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [0.3, 0.3, 0.3],
    "position": [0, .235285, 0],
    "physics": undefined,
    "type": "OBJ",
    "ref_pointer": undefined,
    "lighting_mode": "IBL",
    "spotlight_position_y": 29.2,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fdesk2%2Fdesk.mtl?alt=media&token=9126b041-2c55-4c01-92c9-404547da35d7' },],
  },
  {
    "name": "icecream_man",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/sofa/Sofa_big.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fsofa_big%2FSofa_big.obj?alt=media&token=583594cd-6996-49dd-978b-3e94e3154a83' },
    "materials": "white",
    //  "animation":{name:"02", delay:0, loop:true, run:true},
    "scale": [.2, .2, .2],
    "position": [0, 5 * POSITION_OFFSET, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "shadow_width": 23.5,
    "shadow_height": 3,
    "spotlight_position_y": 29.2,
    "lighting_mode": "IBL",
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fsofa_big%2FSofabig.mtl?alt=media&token=b310aeaf-a0c3-4af8-bc5c-6531a8d527f6' },],
  },
  {
    "name": "emoji_smile",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img": require("./res/models/bed/bed.jpg"),
    "obj": { uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fbed%2Fbed.obj?alt=media&token=cdcf65b0-697e-40e7-95cf-0c0f9185eea2' },
    "materials": "white",
    "animation": { name: "02", delay: 0, loop: true, run: true },
    "scale": [.2, .2, .2],
    "position": [0, .497823 + POSITION_OFFSET, 0],
    "type": "OBJ",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 25.2,
    "lighting_mode": "IBL",
    "shadow_width": 20.5,
    "shadow_height": 10.5,
    "posx0": -1.6,
    "posx1": -0.8,
    "posx2": 0,
    "posx3": 0.8,
    "posx4": 1.6,
    "posy": 3,
    "posz": 0,
    "resources": [{ uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Fbed%2Fbed.mtl?alt=media&token=89438d6b-6701-4bfb-9b57-40a3a576994b' },],
  },

  // {
  //   "name": "object_bday_cake",
  //   "selected": false,
  //   "loading": LoadingConstants.NONE,
  //   "icon_img":require("./res/icon_object_cake.png"),
  //   "obj": {uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Funtitled.obj?alt=media&token=e2cd6329-69db-41c0-901a-4cf825830919'},
  //   "materials": null,
  //   "animation": null,
  //   "scale": [.2, .2, .2],
  //   "position" : [0, .165234, 0],
  //   "type" : "VRX",
  //   "emitter_name": "BirthdayCakeEmitter",
  //   "physics": undefined,
  //   "ref_pointer": undefined,
  //   "lighting_mode": "IBL",
  //   "spotlight_position_y": 9.2,
  //   "resources": [{uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Funtitled.mtl?alt=media&token=53f4fc4f-b8d9-4ea3-9c1a-b432e114a7c3'},],
  // },
  // {
  //   "name": "object_flowers",
  //   "selected": false,
  //   "loading": LoadingConstants.NONE,
  //   "icon_img":require("./res/icon_object_flowers.png"),
  //   "obj": {uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Funtitled.obj?alt=media&token=e2cd6329-69db-41c0-901a-4cf825830919'},
  //   "materials": null,
  //   "animation":{name:"02", delay:0, loop:true, run:true},
  //   "scale": [.6, .6, .6],
  //   "position" : [0, .290760, 0],
  //   "type" : "VRX",
  //   "physics": undefined,
  //   "ref_pointer": undefined,
  //   "lighting_mode": "IBL",
  //   "resources": [{uri: 'https://firebasestorage.googleapis.com/v0/b/interiorproject-2567f.appspot.com/o/3d%20models%2Funtitled.mtl?alt=media&token=53f4fc4f-b8d9-4ea3-9c1a-b432e114a7c3'},],
  // },
]
const getCircularReplacer = () => {
  const seen = new WeakSet();
  return (key, value) => {
    if (typeof value === "object" && value !== null) {
      if (seen.has(value)) {
        return;
      }
      seen.add(value);
    }
    return value;
  };
};



module.exports = {
  getModelArray: function () {
    return ModelItems;
  }
};
