item {
  id: 1
  name: 'chair'
}

item {
  id: 2
  name: 'bed'
}

item {
  id: 3
  name: 'table'
}

item {
  id: 4
  name: 'sofa'
}

item {
  id: 5
  name: 'door'
}

item {
  id: 6
  name: 'side table'
}